In [1]:
import numpy
import os

water_file = os.path.join('data','water.xyz')

wateratoms = numpy.genfromtxt(fname=water_file,skip_header=2,dtype='unicode')

print(wateratoms)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [2]:
data = wateratoms[:,1:]
data = data.astype(numpy.float)
headers = wateratoms[:,0]
print(data)
print(headers)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
['O' 'H1' 'H2']


In [3]:
print(abs(-sum(data[0])))

0.9583349999999999


In [22]:
filewrite = open('water bond lengths','w+')
for i in range(0,3):
    for j in range(0,3):
        bondlength = numpy.sqrt(sum((data[i]-data[j])**2))
        print(F'{headers[i]} to {headers[j]} : {bondlength:.3f}')
        filewrite.write(F'{headers[i]} to {headers[j]} : {bondlength:.3f}\n')
filewrite.close()
        

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


## Trials

In [7]:
print(data[0]-data[0])

[0. 0. 0.]


In [ ]:
headers = wateratoms[:,0]
print(headers)

In [ ]:
print(data[0])

In [ ]:
column_length = len(data[0])
print(column_length)

In [ ]:
numpy.sqrt(numpy.sum(data[2]))

In [ ]:
numpy.sum(data[2]**2)

In [ ]:
numpy.sqrt(numpy.sum(data[2]**2))